name: Build LaTeX project
on: [push]

jobs:
  build-resume:
    runs-on: ubuntu-latest
    name: Build project and push artifact

    container:
      image: danteev/texlive:latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Build project
      working-directory: ./tex
      run: make doc

    - name: Upload artifact
      working-directory: ./tex
      uses: actions/upload-artifact@v2
      with:
        name: proyecto.pdf
        path: ./proyecto.pdf