name: Build LaTeX project
on: [push]

jobs:
  build-resume:
    runs-on: ubuntu-latest
    name: Build project and push artifact

    container:
      image: danteev/texlive:latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Build project
      working-directory: ./tex
      run: make doc

    - name: Set date
      run: echo "$(date +"%D-%T")" >> ${DATETIME}

    - name: Upload project artifact
      uses: actions/upload-artifact@v3
      with:
        name: proyecto_${DATETIME}
        path: ./tex/proyecto.pdf