name: Check spelling
on: 
  push:
    paths-ignore:
      - '**/README.md'

jobs:
  build-resume:
    runs-on: ubuntu-latest
    name: Check spelling

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Install aspell
      run: sudo apt install aspell aspell-es aspell-en

    - name: Check spelling
      working-directory: ./tex
      run: make spell
